# Generated by Django 5.0.6 on 2024-06-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_test_user_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='user_for',
            field=models.ManyToManyField(blank=True, null=True, to='app.customuser', verbose_name='Для кого тест'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='test',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to='app.customuser', verbose_name='Прошли тест'),
        ),
    ]
